spring.application.name=hostly-reservas-service
server.port=8082

# 1. Configuración de Base de Datos (Supabase)

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=

# Evita que Spring intente buscar archivos data.sql viejos
spring.sql.init.mode=never

# 2. Configuración de JPA / Hibernate

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# VALIDATE: Comprueba que tus clases Java coincidan con tus tablas en Supabase
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=db_reservas

# Oculta la alerta molesta de open-in-view en la consola
spring.jpa.open-in-view=false

# 3. Flyway CONFIGURADO Y ACTIVADO

spring.flyway.enabled=true
spring.flyway.default-schema=db_reservas
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# 4. Logs y Colores

logging.level.root=INFO
logging.level.org.hibernate.SQL=INFO
spring.output.ansi.enabled=ALWAYS