spring.application.name=hostly-reservas-service
server.port=8083

# Logs y Estilos de Consola
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.root=INFO
spring.output.ansi.enabled=ALWAYS

# Configuración de Base de Datos (Supabase)

spring.datasource.url=jdbc:postgresql://db.fntbzznwdanouuqpzxfv.supabase.co:5432/postgres?currentSchema=db_reservas
spring.datasource.username=postgres
spring.datasource.password=Hostly.pets26
spring.datasource.driver-class-name=org.postgresql.Driver

# Evita que Spring intente buscar archivos data.sql viejos al arrancar
spring.sql.init.mode=never

# No se indica ningún archivo data.sql para cargar datos iniciales
spring.sql.init.data-locations=

# Configuración de JPA / Hibernate
spring.jpa.defer-datasource-initialization=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=db_reservas

#Configuración de Flyway (Migraciones de Reservas)
spring.flyway.enabled=true
spring.flyway.default-schema=db_reservas
spring.flyway.schemas=db_reservas
spring.flyway.locations=classpath:db/migration

# ------------------------------------------------------------------

# Configuración de Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# ------------------------------------------------------------------

# URL de Eureka Server para el Service Discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
