CREATE SCHEMA IF NOT EXISTS bd_propiedades;

CREATE TABLE IF NOT EXISTS bd_propiedades.tipo_propiedad (
    id_tipo_propiedad BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tipo_propiedad VARCHAR(50) NOT NULL UNIQUE
);