CREATE TABLE IF NOT EXISTS bd_propiedades.tipo_mascota (
    id_tipo_mascota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tipo_mascota VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS bd_propiedades.tamano_mascota (
    id_tamano_mascota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tamano_mascota VARCHAR(50) NOT NULL UNIQUE
);