CREATE TABLE IF NOT EXISTS bd_propiedades.propiedad (
    id_propiedad BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_anfitrion BIGINT NOT NULL,
    titulo VARCHAR(100) NOT NULL,
    descripcion VARCHAR(500) NOT NULL,
    direccion VARCHAR(150) NOT NULL,
    ciudad VARCHAR(80) NOT NULL,
    precio_noche DOUBLE PRECISION NOT NULL,
    tiene_patio BOOLEAN NOT NULL,
    costo_extra_mascota DOUBLE PRECISION NOT NULL,
    disponible BOOLEAN NOT NULL,
    id_tipo_propiedad BIGINT NOT NULL,
    id_tipo_mascota BIGINT NOT NULL,
    id_tamano_mascota BIGINT NOT NULL,

    CONSTRAINT fk_tipo_propiedad FOREIGN KEY (id_tipo_propiedad)
        REFERENCES bd_propiedades.tipo_propiedad(id_tipo_propiedad),

    CONSTRAINT fk_tipo_mascota FOREIGN KEY (id_tipo_mascota)
        REFERENCES bd_propiedades.tipo_mascota(id_tipo_mascota),

    CONSTRAINT fk_tamano_mascota FOREIGN KEY (id_tamano_mascota)
        REFERENCES bd_propiedades.tamano_mascota(id_tamano_mascota)
);