#Nombre de la aplicación o microservicio
#Sirve para identificar este servicio dentro del proyecto
spring.application.name=hostly_propiedades_service

#Puerto donde se ejecutará este microservicio
#Al abrilo en el navegador o Postman será: http://localhost:8081
server.port=8081

# ------------------------------------------------------------------

#Muestra información de: Request HTTP y Controllers
#INFO: muestra información importante sin llenar demasiado la consola
logging.level.org.springframework.web=INFO

#Muestra las consultas SQL que ejecuta Hibernate/JPA
#Sirve para revisar qué consultas se están haciendo en la base de datos
logging.level.org.hibernate.SQL=INFO

#Define el nivel general de logs de toda la app
#INFO: muestra mensajes informativos, advertencias y errores
logging.level.root=INFO

#Activa colores en la consola: es más facil leer lo que pasa
spring.output.ansi.enabled=ALWAYS


# ------------------------------------------------------------------

#URL de conexión a la base de datos PostgreSQL en Supabase
#Indica el servidor, puerto y nombre de la base de datos.
spring.datasource.url=

#Usuario de la base de datos
spring.datasource.username=

#Contraseña de la base de datos
spring.datasource.password=

#Driver que permite a Spring Boot conectarse a PostgreSQL
spring.datasource.driver-class-name=

# ------------------------------------------------------------------

#Evita que Spring ejecute automáticamente scripts SQL al iniciar
spring.sql.init.mode=never

#No se indica ningún archivo data.sql para cargar datos iniciales
spring.sql.init.data-locations=

# ------------------------------------------------------------------

#Indica que JPA no debe esperar a que se inicialicen scripts SQL antes de arrancar
spring.jpa.defer-datasource-initialization=false

#Formatea las consultas SQL en consola para que sean más fáciles de leer
spring.jpa.properties.hibernate.format_sql=true

#Indica que Hibernate solo validará si las tablas coinciden con las entidades
#No crea ni modifica tablas automáticamente
spring.jpa.hibernate.ddl-auto=validate

#Dialecto de Hibernate para PostgreSQL
#Le dice a Hibernate cómo escribir SQL compatible con PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Muestra en consola las consultas SQL ejecutadas por JPA
spring.jpa.show-sql=true

#Define el esquema de PostgreSQL que usrá Hibernate por defecto
#En este caso, trabajará dentro del esquema db_propiedades
spring.jpa.properties.hibernate.default_schema=db_propiedades

# ------------------------------------------------------------------

#Activa Flyway para manejar migraciones de base de datos
spring.flyway.enabled=true

#Esquema donde Flyway aplicará las migraciones
spring.flyway.default-schema=db_propiedades

#Lista de esquemas que Flyway administrará
spring.flyway.schemas=db_propiedades

#Carpeta donde estarán los archivos de migración SQL
spring.flyway.locations=classpath:db/migration
